### ISSUE TITLE
There is a bug in code

### ISSUE THREAD

**Issue by LiteraryBeetle** [MaxReimann/Shot-Boundary-Detection#1]
Hi, I got the following error when making...
**************************************************************************************************************************
[  4%] Building CXX object CMakeFiles/sbd.dir/src/hard_cut/hardcut_detection.cpp.o
In file included from /myfilepath/Shot-Boundary-Detection-master/src/hard_cut/hardcut_detection.cpp:11:0:
/myfilepath/Shot-Boundary-Detection-master/src/hard_cut/svm/svm.hpp:18:9: error: ‘CvSVMParams’ does not name a type
         CvSVMParams m_params;
         ^
/myfilepath/Shot-Boundary-Detection-master/hard_cut/svm/svm.hpp:19:9: error: ‘CvSVM’ does not name a type
         CvSVM m_svm;
         ^
CMakeFiles/sbd.dir/build.make:110: recipe for target 'CMakeFiles/sbd.dir/src/hard_cut/hardcut_detection.cpp.o' failed
make[2]: *** [CMakeFiles/sbd.dir/src/hard_cut/hardcut_detection.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sbd.dir/all' failed
make[1]: *** [CMakeFiles/sbd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
***************************************************************************************************************************
Could you help check the error? Thank you.

**Comment by Lixissimus** [comment]
This could be a problem with your OpenCV version. Many things changed with v3.0 including class names and I think we used a version 2.x.
