### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by LiuYangICV** [MaxReimann/Shot-Boundary-Detection#2]
Hello, I make the program successfully in Ubuntu, but I failed to run it.
What should I do after making it ?
Thank you!

**Comment by Lixissimus** [comment]
Did you follow the steps in the readme?

**Comment by MaxReimann** [comment]
@LiuYangICV Is there an error when you try executing or can we close the issue ?

**Comment by LiuYangICV** [comment]
Oh sorry, I made a mistake stupidly. I can run it now. 
Thanks for your prompt replies and the issue can be closed now.
